account/urls.py
from .views import login_page, register_page, logout_view
from django.urls import path

app_name = "Account"

urlpatterns = [
    path('login', login_page, name="Login"),
    path('register', register_page, name="Register"),
    path('logout', logout_view, name="Logout"),
]

chat/urls.py
from django.urls import path
from .views import room_page

app_name = "ChatApp"

urlpatterns = [
    path("chat/<str:room_name>", room_page, name="RoomPage"),
]

messenger/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from messenger import settings
from django.urls import path, include
from .views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name="HomePage"),
    path('', include("account.urls", namespace="Account")),
    path('', include("chat.urls", namespace="ChatApp")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/shared/_FooterReferences.html
<script src='https://use.fontawesome.com/releases/v5.0.13/js/all.js'></script>

templates/shared/_HeaderReferences.html
{% load static %}

<link rel="stylesheet" href="{% static "css/style.css" %}">

templates/shared/_MainLayout.html
{% load render_partial %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% include "shared/_HeaderReferences.html" %}
    {% block header_ref %}{% endblock %}
</head>
<body>

{% render_partial "messenger.views.header" reqpath=request.path %}

{% block content %}{% endblock %}

{% include "shared/_FooterReferences.html" %}
{% block footer_ref %}{% endblock %}
</body>
</html>

templates/shared/header.html
{% url "Account:Login" as login_url %}
{% url "Account:Register" as register_url %}
{% url "Account:Logout" as logout_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Messenger</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link {% if reqpath == "/" %}active{% endif %}" aria-current="page" href="/">Home</a>
                </li>

                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {% if reqpath == login_url %}active{% endif %}"
                           href="{{ login_url }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if reqpath == register_url %}active{% endif %}"
                           href="{{ register_url }}">Register</a>
                    </li>
                {% endif %}

                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ logout_url }}">Logout</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>